### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/wp-database-backup#3]
When click on 'Create New Backup' button inside WP ALL Backup dashboard. 

2.  Fatal error: Uncaught Error: time() expects exactly 0 arguments, 1 given
in D:\XAMPP\htdocs\magazine3\wp-content\plugins\wp-all-backup-plus\includes\admin\class-admin-settings.php on line 207

3.  Fatal error: Uncaught Error: implode(): Argument #2 ($array) must be of type ?array, bool given
in D:\XAMPP\htdocs\magazine3\wp-content\plugins\wp-all-backup-plus\includes\admin\class-admin-settings.php on line 453

4. Fatal error: Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, bool given in /home/customer/www/ahmedk31.sg-host.com/public_html/wp-content/plugins/wp-all-backup-plus/includes/admin/create-backup.php:240 Stack trace: #0 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-content/plugins/wp-all-backup-plus/includes/admin/create-backup.php(240): array_column(false, 'filename') #1 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-content/plugins/wp-all-backup-plus/includes/admin/class-admin-settings.php(50): include('/home/customer/...') #2 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-includes/class-wp-hook.php(308): WPALLMenu::renderAdminPage('') #3 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/customer/www/ahmedk31.sg-host.com/public_html/wp-admin/admin.php(259): do_action('toplevel_page_w...') #6 {main} thrown in /home/customer/www/ahmedk31.sg-host.com/public_html/wp-content/plugins/wp-all-backup-plus/includes/admin/create-backup.php on line 240

**Comment by Sanjeevsetu** [comment]
its done
